spring:
  datasource:
    url: jdbc:h2:mem:keymaster
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
logging:
  level:
    '[fi.pmh]': 'DEBUG'
    '[org.springframework.security]': 'DEBUG'